const homedir = require('homedir')
const path = require('path')
const Utils = require('./utils')
const fs = require('./utils/fs')
const pkg = require('../package')

const config = {
  onlyDir: 1,
  onlyFile: 2,

  setPaths: (container = `${homedir()}/.secrez`) => {
    config.root = path.basename(container)
    config.dataPath = path.join(container, 'data')
    config.tmpPath = path.join(config.dataPath, '.tmp')
    config.workingDir = '/'
    config.localWorkingDir = homedir()
    config.envPath = path.join(container, '.env.json')
    config.confPath = path.join(config.dataPath, 'conf.json')
    fs.emptyDirSync(config.tmpPath)
    fs.ensureDirSync(config.dataPath)
    let readmePath = path.join(container, 'README')
    if (!fs.existsSync(readmePath)) {
      fs.writeFileSync(readmePath, `
This folder has been generated by ${Utils.capitalize(pkg.name)} v${pkg.version}.
It contains your secret database. 
Be very careful, and don't touch anything :o)
`, 'utf-8')
    }
  }

}

module.exports = config
