const path = require('path')
const Utils = require('./utils')
const fs = require('./utils/fs')
const pkg = require('../package')

const config = {

  onlyDir: 1,
  onlyFile: 2,

  secrez: {},

  setSecrez: async (
      container,
      localWorkingDir
  ) => {
    let s = config.secrez
    s.root = path.basename(container)
    s.dataPath = path.join(container, 'data')
    s.tmpPath = path.join(s.dataPath, '.tmp')
    s.workingDir = '/'
    s.localWorkingDir = localWorkingDir
    s.envPath = path.join(container, '.env.json')
    s.confPath = path.join(s.dataPath, 'conf.json')
    await fs.emptyDirAsync(s.tmpPath)
    await fs.ensureDirAsync(s.dataPath)
    let readmePath = path.join(container, 'README')
    if (!fs.existsSync(readmePath)) {
      await fs.writeFileAsync(readmePath, `
This folder has been generated by ${Utils.capitalize(pkg.name)} v${pkg.version}.
It contains your secret database. 
Be very careful, and don't touch anything :o)
`, 'utf-8')
    }
  }

}

module.exports = config
