const homedir = require('homedir')
const path = require('path')
const Utils = require('./utils')
const fs = require('./utils/fs')
const pkg = require('../package')

const TRUE = 1
const STRING = 2
const ARRAY = 3
const NUMBER = 4
const BOOL = 5
const OBJECT = 6

const completionTypes = {
  TRUE,
  STRING,
  ARRAY,
  NUMBER,
  BOOL,
  OBJECT
}

const config = {
  completionTypes,
  completion: {
    help: {}
  },
  getVirtualDir: function (dir) {
    if (dir.indexOf(config.dataPath) === 0) {
      return dir.split(config.dataPath)[1]
    } else {
      throw new Error('The directory does not exist in Secrez.')
    }
  }
}

function setPaths(container = `${homedir()}/.secrez`) {
  config.root = path.basename(container)
  config.rootPath = path.dirname(container)
  config.dataPath = path.join(container, 'data')
  config.workingDir = '/'
  config.confPath = path.join(config.dataPath, 'conf.json')
  fs.ensureDirSync(config.dataPath)
  let readmePath = path.join(config.rootPath, 'README')
  if (!fs.existsSync(readmePath)) {
    fs.writeFileSync(readmePath, `
This folder has been generated by ${Utils.capitalize(pkg.name)} v${pkg.version}.
It contains your secret database. 
Be careful and don't touch anything :o)
`, 'utf-8')
  }
}

module.exports = config
module.exports.setPaths = setPaths
